---
name: Slugify Value
on:
  push:
    branches:
      - v1.x
  pull_request:

permissions:
  contents: read

# Disable line length check due to the content of the tests
# yamllint disable rule:line-length
jobs:
  os-testing:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      # Test 1
      - name: Slugify key only
        id: slugify-key-only
        uses: ./
        with:
          key: KEY_ONLY
        env:
          KEY_ONLY: "refs/head/$-Key_Only.test--value-%-+"
      - name: Validate // Slugify key only
        # Disable SC2193 because the first line of the test is flag by shellcheck
        # as the comparison can never be equal but the test pass.
        # Seem a false-positive due to the test context.
        env:
          KEY_ONLY: ${{ env.KEY_ONLY }}
          KEY_ONLY_SLUG: ${{ env.KEY_ONLY_SLUG }}
          KEY_ONLY_SLUG_CS: ${{ env.KEY_ONLY_SLUG_CS }}
          KEY_ONLY_SLUG_URL: ${{ env.KEY_ONLY_SLUG_URL }}
          KEY_ONLY_SLUG_URL_CS: ${{ env.KEY_ONLY_SLUG_URL_CS }}
          STEP_VALUE: ${{ steps.slugify-key-only.outputs.value }}
          STEP_SLUG: ${{ steps.slugify-key-only.outputs.slug }}
          STEP_SLUG_CS: ${{ steps.slugify-key-only.outputs.slug-cs }}
          STEP_SLUG_URL: ${{ steps.slugify-key-only.outputs.slug-url }}
          STEP_SLUG_URL_CS: ${{ steps.slugify-key-only.outputs.slug-url-cs }}
        run: |
          # shellcheck disable=SC2193
          [[ "$KEY_ONLY" == "refs/head/$-Key_Only.test--value-%-+" ]]
          [[ "$KEY_ONLY_SLUG" == "key_only.test--value" ]]
          [[ "$KEY_ONLY_SLUG_CS" == "Key_Only.test--value" ]]
          [[ "$KEY_ONLY_SLUG_URL" == "key-only-test--value" ]]
          [[ "$KEY_ONLY_SLUG_URL_CS" == "Key-Only-test--value" ]]
          [[ "$KEY_ONLY" == "$STEP_VALUE" ]]
          [[ "$KEY_ONLY_SLUG" == "$STEP_SLUG" ]]
          [[ "$KEY_ONLY_SLUG_CS" == "$STEP_SLUG_CS" ]]
          [[ "$KEY_ONLY_SLUG_URL" == "$STEP_SLUG_URL" ]]
          [[ "$KEY_ONLY_SLUG_URL_CS" == "$STEP_SLUG_URL_CS" ]]
        shell: bash

      # Test 2
      - name: Slugify key only with prefix
        uses: ./
        with:
          key: KEY_ONLY_WITH_PREFIX
          prefix: CI_
        env:
          KEY_ONLY_WITH_PREFIX: ${{ env.KEY_ONLY }}
      - name: Validate // Slugify key only with prefix
        env:
          CI_KEY_ONLY_WITH_PREFIX: ${{ env.CI_KEY_ONLY_WITH_PREFIX }}
          CI_KEY_ONLY_WITH_PREFIX_SLUG: ${{ env.CI_KEY_ONLY_WITH_PREFIX_SLUG }}
          CI_KEY_ONLY_WITH_PREFIX_SLUG_CS: ${{ env.CI_KEY_ONLY_WITH_PREFIX_SLUG_CS }}
          CI_KEY_ONLY_WITH_PREFIX_SLUG_URL: ${{ env.CI_KEY_ONLY_WITH_PREFIX_SLUG_URL }}
          CI_KEY_ONLY_WITH_PREFIX_SLUG_URL_CS: ${{ env.CI_KEY_ONLY_WITH_PREFIX_SLUG_URL_CS }}
          KEY_ONLY: ${{ env.KEY_ONLY }}
          KEY_ONLY_SLUG: ${{ env.KEY_ONLY_SLUG }}
          KEY_ONLY_SLUG_CS: ${{ env.KEY_ONLY_SLUG_CS }}
          KEY_ONLY_SLUG_URL: ${{ env.KEY_ONLY_SLUG_URL }}
          KEY_ONLY_SLUG_URL_CS: ${{ env.KEY_ONLY_SLUG_URL_CS }}
        run: |
          [[ "$CI_KEY_ONLY_WITH_PREFIX" == "$KEY_ONLY" ]]
          [[ "$CI_KEY_ONLY_WITH_PREFIX_SLUG" == "$KEY_ONLY_SLUG" ]]
          [[ "$CI_KEY_ONLY_WITH_PREFIX_SLUG_CS" == "$KEY_ONLY_SLUG_CS" ]]
          [[ "$CI_KEY_ONLY_WITH_PREFIX_SLUG_URL" == "$KEY_ONLY_SLUG_URL" ]]
          [[ "$CI_KEY_ONLY_WITH_PREFIX_SLUG_URL_CS" == "$KEY_ONLY_SLUG_URL_CS" ]]
        shell: bash

      # Test 3
      - name: Slugify key/value
        uses: ./
        with:
          key: KEY_VALUE
          value: "Never gonna give you up Never gonna let you down"
      - name: Validate // Slugify key/value
        env:
          KEY_VALUE: ${{ env.KEY_VALUE }}
          KEY_VALUE_SLUG: ${{ env.KEY_VALUE_SLUG }}
          KEY_VALUE_SLUG_CS: ${{ env.KEY_VALUE_SLUG_CS }}
          KEY_VALUE_SLUG_URL: ${{ env.KEY_VALUE_SLUG_URL }}
          KEY_VALUE_SLUG_URL_CS: ${{ env.KEY_VALUE_SLUG_URL_CS }}
        run: |
          [[ "$KEY_VALUE" == "Never gonna give you up Never gonna let you down" ]]
          [[ "$KEY_VALUE_SLUG" == "never-gonna-give-you-up-never-gonna-let-you-down" ]]
          [[ "$KEY_VALUE_SLUG_CS" == "Never-gonna-give-you-up-Never-gonna-let-you-down" ]]
          [[ "$KEY_VALUE_SLUG_URL" == "never-gonna-give-you-up-never-gonna-let-you-down" ]]
          [[ "$KEY_VALUE_SLUG_URL_CS" == "Never-gonna-give-you-up-Never-gonna-let-you-down" ]]
        shell: bash

      # Test 4
      - name: Slugify with another max length
        uses: ./
        with:
          key: ANOTHER_MAX_LENGTH
          value: "Never gonna give you up Never gonna let you down"
          slug-maxlength: 24
      - name: Validate // Slugify with another max length
        env:
          ANOTHER_MAX_LENGTH: ${{ env.ANOTHER_MAX_LENGTH }}
          ANOTHER_MAX_LENGTH_SLUG: ${{ env.ANOTHER_MAX_LENGTH_SLUG }}
          ANOTHER_MAX_LENGTH_SLUG_CS: ${{ env.ANOTHER_MAX_LENGTH_SLUG_CS }}
          ANOTHER_MAX_LENGTH_SLUG_URL: ${{ env.ANOTHER_MAX_LENGTH_SLUG_URL }}
          ANOTHER_MAX_LENGTH_SLUG_URL_CS: ${{ env.ANOTHER_MAX_LENGTH_SLUG_URL_CS }}
        run: |
          [[ "$ANOTHER_MAX_LENGTH" == "Never gonna give you up Never gonna let you down" ]]
          [[ "$ANOTHER_MAX_LENGTH_SLUG" == "never-gonna-give-you-up" ]]
          [[ "$ANOTHER_MAX_LENGTH_SLUG_CS" == "Never-gonna-give-you-up" ]]
          [[ "$ANOTHER_MAX_LENGTH_SLUG_URL" == "never-gonna-give-you-up" ]]
          [[ "$ANOTHER_MAX_LENGTH_SLUG_URL_CS" == "Never-gonna-give-you-up" ]]
        shell: bash

      # Test 5
      - name: Slugify with no limit on max length
        uses: ./
        with:
          key: NO_MAX_LENGTH
          value: "Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you"
          slug-maxlength: "nolimit"
      - name: Validate // Slugify with no limit on max length
        env:
          NO_MAX_LENGTH: ${{ env.NO_MAX_LENGTH }}
          NO_MAX_LENGTH_SLUG: ${{ env.NO_MAX_LENGTH_SLUG }}
          NO_MAX_LENGTH_SLUG_CS: ${{ env.NO_MAX_LENGTH_SLUG_CS }}
          NO_MAX_LENGTH_SLUG_URL: ${{ env.NO_MAX_LENGTH_SLUG_URL }}
          NO_MAX_LENGTH_SLUG_URL_CS: ${{ env.NO_MAX_LENGTH_SLUG_URL_CS }}
        run: |
          [[ "$NO_MAX_LENGTH" == "Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you" ]]
          [[ "$NO_MAX_LENGTH_SLUG" == "never-gonna-give-you-up-never-gonna-let-you-down-never-gonna-run-around-and-desert-you-never-gonna-make-you-cry-never-gonna-say-goodbye-never-gonna-tell-a-lie-and-hurt-you" ]]
          [[ "$NO_MAX_LENGTH_SLUG_CS" == "Never-gonna-give-you-up-Never-gonna-let-you-down-Never-gonna-run-around-and-desert-you-Never-gonna-make-you-cry-Never-gonna-say-goodbye-Never-gonna-tell-a-lie-and-hurt-you" ]]
          [[ "$NO_MAX_LENGTH_SLUG_URL" == "never-gonna-give-you-up-never-gonna-let-you-down-never-gonna-run-around-and-desert-you-never-gonna-make-you-cry-never-gonna-say-goodbye-never-gonna-tell-a-lie-and-hurt-you" ]]
          [[ "$NO_MAX_LENGTH_SLUG_URL_CS" == "Never-gonna-give-you-up-Never-gonna-let-you-down-Never-gonna-run-around-and-desert-you-Never-gonna-make-you-cry-Never-gonna-say-goodbye-Never-gonna-tell-a-lie-and-hurt-you" ]]
        shell: bash

      # Test 6
      - name: Slugify with empty max length
        id: slugify-with-empty-max-length
        uses: ./
        with:
          key: EMPTY_MAXLENGTH
          value: some_value
          slug-maxlength: ""
        continue-on-error: true
      - name: Validate // Slugify with empty max length
        env:
          EMPTY_MAXLENGTH: ${{ env.EMPTY_MAXLENGTH }}
          EMPTY_MAXLENGTH_SLUG: ${{ env.EMPTY_MAXLENGTH_SLUG }}
          EMPTY_MAXLENGTH_SLUG_CS: ${{ env.EMPTY_MAXLENGTH_SLUG_CS }}
          EMPTY_MAXLENGTH_SLUG_URL: ${{ env.EMPTY_MAXLENGTH_SLUG_URL }}
          EMPTY_MAXLENGTH_SLUG_URL_CS: ${{ env.EMPTY_MAXLENGTH_SLUG_URL_CS }}
          STEP_OUTCOME: ${{ steps.slugify-with-empty-max-length.outcome }}
          STEP_CONCLUSION: ${{ steps.slugify-with-empty-max-length.conclusion }}
        run: |
          [[ -z "$EMPTY_MAXLENGTH" ]]
          [[ -z "$EMPTY_MAXLENGTH_SLUG" ]]
          [[ -z "$EMPTY_MAXLENGTH_SLUG_CS" ]]
          [[ -z "$EMPTY_MAXLENGTH_SLUG_URL" ]]
          [[ -z "$EMPTY_MAXLENGTH_SLUG_URL_CS" ]]
          [[ "$STEP_OUTCOME" == "failure" ]]
          [[ "$STEP_CONCLUSION" == "success" ]]
        shell: bash

      # Test 7
      - name: Slugify with wrong max length
        id: slugify-with-wrong-max-length
        uses: ./
        with:
          key: WRONG_MAXLENGTH
          value: some_value
          slug-maxlength: "wrong"
        continue-on-error: true
      - name: Validate // Slugify with wrong max length
        env:
          WRONG_MAXLENGTH: ${{ env.WRONG_MAXLENGTH }}
          WRONG_MAXLENGTH_SLUG: ${{ env.WRONG_MAXLENGTH_SLUG }}
          WRONG_MAXLENGTH_SLUG_CS: ${{ env.WRONG_MAXLENGTH_SLUG_CS }}
          WRONG_MAXLENGTH_SLUG_URL: ${{ env.WRONG_MAXLENGTH_SLUG_URL }}
          WRONG_MAXLENGTH_SLUG_URL_CS: ${{ env.WRONG_MAXLENGTH_SLUG_URL_CS }}
          STEP_OUTCOME: ${{ steps.slugify-with-wrong-max-length.outcome }}
          STEP_CONCLUSION: ${{ steps.slugify-with-wrong-max-length.conclusion }}
        run: |
          [[ -z "$WRONG_MAXLENGTH" ]]
          [[ -z "$WRONG_MAXLENGTH_SLUG" ]]
          [[ -z "$WRONG_MAXLENGTH_SLUG_CS" ]]
          [[ -z "$WRONG_MAXLENGTH_SLUG_URL" ]]
          [[ -z "$WRONG_MAXLENGTH_SLUG_URL_CS" ]]
          [[ "$STEP_OUTCOME" == "failure" ]]
          [[ "$STEP_CONCLUSION" == "success" ]]
        shell: bash

      # Test 8
      - name: Slugify key without env publication
        id: slugify-key-without-env-publication
        uses: ./
        with:
          key: KEY_WITHOUT_ENV_PUBLICATION
          publish-env: false
        env:
          KEY_WITHOUT_ENV_PUBLICATION: "Never gonna give you up"
      - name: Validate // Slugify key without env publication
        env:
          KEY_WITHOUT_ENV_PUBLICATION: ${{ env.KEY_WITHOUT_ENV_PUBLICATION }}
          KEY_WITHOUT_ENV_PUBLICATION_SLUG: ${{ env.KEY_WITHOUT_ENV_PUBLICATION_SLUG }}
          KEY_WITHOUT_ENV_PUBLICATION_SLUG_CS: ${{ env.KEY_WITHOUT_ENV_PUBLICATION_SLUG_CS }}
          KEY_WITHOUT_ENV_PUBLICATION_SLUG_URL: ${{ env.KEY_WITHOUT_ENV_PUBLICATION_SLUG_URL }}
          KEY_WITHOUT_ENV_PUBLICATION_SLUG_URL_CS: ${{ env.KEY_WITHOUT_ENV_PUBLICATION_SLUG_URL_CS }}
          STEP_VALUE: ${{ steps.slugify-key-without-env-publication.outputs.value }}
          STEP_SLUG: ${{ steps.slugify-key-without-env-publication.outputs.slug }}
          STEP_SLUG_CS: ${{ steps.slugify-key-without-env-publication.outputs.slug-cs }}
          STEP_SLUG_URL: ${{ steps.slugify-key-without-env-publication.outputs.slug-url }}
          STEP_SLUG_URL_CS: ${{ steps.slugify-key-without-env-publication.outputs.slug-url-cs }}
        run: |
          [[ -z "$KEY_WITHOUT_ENV_PUBLICATION" ]]
          [[ -z "$KEY_WITHOUT_ENV_PUBLICATION_SLUG" ]]
          [[ -z "$KEY_WITHOUT_ENV_PUBLICATION_SLUG_CS" ]]
          [[ -z "$KEY_WITHOUT_ENV_PUBLICATION_SLUG_URL" ]]
          [[ -z "$KEY_WITHOUT_ENV_PUBLICATION_SLUG_URL_CS" ]]
          [[ "$STEP_VALUE" == "Never gonna give you up" ]]
          [[ "$STEP_SLUG" == "never-gonna-give-you-up" ]]
          [[ "$STEP_SLUG_CS" == "Never-gonna-give-you-up" ]]
          [[ "$STEP_SLUG_URL" == "never-gonna-give-you-up" ]]
          [[ "$STEP_SLUG_URL_CS" == "Never-gonna-give-you-up" ]]
        shell: bash

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      id-token: write
      packages: write
    concurrency:
      group: release-${{ github.ref }}
    needs:
      - os-testing
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      # Release
      - name: Release this GitHub Action
        uses: rlespinasse/release-that@f4912d4053839003bb368e9c7067b071ccb1c146 # v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
